apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-worker01
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/storage/consul
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-worker02
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/storage/consul
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-worker03
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/storage/consul
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker03
