apiVersion: v1
kind: Service
metadata:
  name: consul-https
  labels:
    name: consul-https
spec:
  type: NodePort
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30850
  selector:
    app: consul
