
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - name: vault-port
    port: 8200
    targetPort: 8200
    nodePort: 30820
    protocol: TCP
